### ISSUE TITLE
Pin ALL versions for tools and community GH Actions to specific versions.

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2229]
Make sure all of Armada workflows use pinned versions of actions.

Instead of:
```
jobs:
  go-lint:
    # TODO(JayF): Configure this to only run when golang code has changed
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.18' ]
    steps:
      - uses: actions/checkout@v3
```

use:
```
jobs:
  go-lint:
    # TODO(JayF): Configure this to only run when golang code has changed
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.18' ]
    steps:
      - uses: actions/checkout@v3.3.0
```
