### ISSUE TITLE
Port 6443 already in use - kind.yaml

### ISSUE THREAD

**Issue by anshgoyalevil** [armadaproject/armada#2762]
**Describe the bug**
Port 6443 is the default port the Kubernetes control plane is bound to. Docker Desktop forwards this port on the host which facilitates the communication with the control plane as it would be installed directly on the host.

This is the same port being used inside the kind.yaml file due to which, the error occurs while creating a kind pod over this pod using mage file.

**Files Or Markdown that can reproduce the issue**
https://github.com/armadaproject/armada/blob/master/e2e/setup/kind.yaml
- run the command ```mage localdev full```
- if you are using docker desktop with k8s enabled, an error will occur saying that the port 6443 is already in use.

**Expected behavior**
There should be no error

**Actual behavior**
As above

**Additional context**
We can use another hostPort, like ```6444``` for example, while still using 6443 as a container port

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-548) by [Unito](https://www.unito.io)

**Comment by anshgoyalevil** [comment]
@kannon92 Should I go ahead and create a PR changing the control plane hostPort to 6444. Or any other suggestion you would like to add?

**Comment by kannon92** [comment]
> @kannon92 Should I go ahead and create a PR changing the control plane hostPort to 6444. Or any other suggestion you would like to add?

This seems to be solveable via documentation.  We can't predict that all these ports are free for any user but it is easy to modify your docker-desktop environment or the kind control plan to use a different port.  Maybe we can have a troubleshooting section for localdev and mention ways to troubleshoot this error?

@Sharpz7 WDYT?

**Comment by Sharpz7** [comment]
Yeah, so I have changed this before, by changing https://github.com/armadaproject/armada/blob/master/e2e/setup/kind.yaml

```yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: armada-test
nodes:
- role: worker
  image: kindest/node:v1.24.7
- role: control-plane
  image: kindest/node:v1.24.7
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    # To speed up tests, reduce request timeout from the default 2m.
    runtimeRequestTimeout: "30s"
  extraPortMappings:
  - containerPort: 80 # port of the nginx ingress controller
    hostPort: 5001 # expose ingresses on localhost:5001
    protocol: TCP
  - containerPort: 11000 # arbitrary port used to test "node port services"
    hostPort: 11000 # expose service on localhost:3000
    protocol: TCP
  - containerPort: 6443 # control plane
    hostPort: 6443  # exposes control plane on localhost:6443
    protocol: TCP
```

Becomes...
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: armada-test
networking:
  apiServerPort: 6443
nodes:
- role: worker
  image: kindest/node:v1.24.7
- role: control-plane
  image: kindest/node:v1.24.7
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: KubeletConfiguration
    # To speed up tests, reduce request timeout from the default 2m.
    runtimeRequestTimeout: "30s"
  extraPortMappings:
  - containerPort: 80 # port of the nginx ingress controller
    hostPort: 5001 # expose ingresses on localhost:5001
    protocol: TCP
  - containerPort: 11000 # arbitrary port used to test "node port services"
    hostPort: 11000 # expose service on localhost:3000
    protocol: TCP
 ```
 
 To generalise this would be more tricky, maybe something like envsubst with a mage target to specify the port?
