### ISSUE TITLE
armadactl submit documentation out of date

### ISSUE THREAD

**Issue by Sovietaced** [armadaproject/armada#3883]
`armadactl submit` help text is as follows

```
Submit jobs to armada from file.

Example jobs.yaml:

jobs:
- queue: test
        priority: 0
        jobSetId: set1
        podSpec:
        ... kubernetes pod spec ...

Usage:
  armadactl submit ./path/to/jobs.yaml [flags]
```

The reality is that the format must actually be closer to
```
queue: compute
jobSetId: run-id-here
jobs:
  - namespace: compute
    podSpec:
```

The `queue`, `jobSetId` are specified in different places. Also even if you try to configure the priority correctly it is never passed to the submit API call. https://github.com/armadaproject/armada/blob/master/pkg/client/domain/types.go#L36-L39
