### ISSUE TITLE
Add env variable/secret support for Postgres password

### ISSUE THREAD

**Issue by arosberg** [armadaproject/armada#4345]
### Is your feature request related to a problem? Please describe

Currently, the `applicationConfig.postgres.connection` field in the Armada configuration requires the PostgreSQL password to be specified directly in plaintext. This is problematic in GitOps environments (e.g., using Flux or ArgoCD), where we want to avoid storing secrets in Git or rendered manifests.

There’s no supported way (That I can find) to reference Kubernetes secrets or environment variables for injecting the PostgreSQL password, making secure deployment difficult without custom patching.

---

### Describe the solution you'd like

I’d like support for securely injecting the PostgreSQL password using an environment variable, such that the password is **not** included directly in the config.

Example:

```yaml
postgres:
  connection:
    host: postgresql.armada-deps.svc.cluster.local
    port: 5432
    user: postgres
    passwordFromEnvVar: POSTGRES_PASSWORD
    dbname: lookout
```

The application would resolve `POSTGRES_PASSWORD` from the environment at runtime and construct the connection string accordingly.

#### Option 2: Kubernetes Secret reference
Support referencing a secret directly in the configuration. 

```yaml
postgres:
  connection:
    host: postgresql.armada-deps.svc.cluster.local
    port: 5432
    user: postgres
    passwordFromSecret:
      name: my-postgres-secret
      key: postgres-password
    dbname: lookout
```

This would enable GitOps workflows using SealedSecrets, external secret managers, or simply clean separation of secrets from configs.

---

### Describe alternatives you've considered

- Patching the `Deployment` to add the `POSTGRES_PASSWORD` env var and leaving the password field blank. `passwordFromEnvVar` currently has no effect and is not used in the [`CreateConnectionString`](https://github.com/armadaproject/armada/blob/d33a68e48729a2cc788a1396e3abc108841608f9/internal/common/database/functions.go#L18) logic.
- Storing a SealedSecret and patching the CRD with decrypted values, this is fragile and I haven't really gotten it to work correctly with our setup
