### ISSUE TITLE
Lookout OIDC Authentication Mapping to Groups

### ISSUE THREAD

**Issue by washcycle** [armadaproject/armada#4356]
Setting up OIDC authentication for Lookout.

I was able to get the new auth features for OIDC working with help from @dejanzele and associates.

I'd like to be able to map users in my OIDC provider to groups in Armada. 

**Environment**

- Lookout: v0.19.2
- OIDC Provider: Keycloak 26.2.4

**lookout config**
```yaml
apiPort: 8080
auth:
  anonymousAuth: true
corsAllowedOrigins:
- http://localhost
postgres:
  connection:
    dbname: lookout
    host: xxxxxxx
    password: xxxxxxxx
    port: 5432
    sslmode: require
    user: xxxxx
uiConfig:
  oidc:
    authority: https://example.com/realms/apqx
    clientId: armada-client
    scope: openid profile email
  oidcEnabled: true
```

I assume I need configuration under the application config `auth` item or perhaps another scope to pull in user groups.

Another question I have is the `auth` section for Lookout is what is authorized against the backend server?

**Comment by dejanzele** [comment]
Hi @washcycle,

Thanks for raising the issue and documenting the auth config!

Does this also need to be configured at top level?
```
auth:
  anonymousAuth: false
  openIdAuth:
    clientId: some-client-armada
    groupsClaim: some-claim
    providerUrl: https://example.idp.net/realms/some-realm
```

We'll try to answer your question for mapping users as soon as possible!
